apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: boriscernak/boce-wac-project-ambulance-ufe
  newName: boriscernak/boce-wac-project-ambulance-ufe # {"$imagepolicy":  "wac-hospital:boce-wac-project-ambulance-ufe:name"}
  newTag: main # {"$imagepolicy": "wac-hospital:boce-wac-project-ambulance-ufe:tag"}
- name: milung/ufe-controller
  newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"}
  newTag: 1.7.3 # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}
- name: boriscernak/boce-wac-project-ambulance-wl-webapi
  newName: boriscernak/boce-wac-project-ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:boce-wac-project-ambulance-webapi:name"}
  newTag: main.20240609.1924 # {"$imagepolicy": "wac-hospital:boce-wac-project-ambulance-webapi:tag"}  
