apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
- name: boriscernak/boce-wac-project-ambulance-ufe
  newName: boriscernak/boce-wac-project-ambulance-ufe # {"$imagepolicy":  "wac-hospital:boce-wac-project-ambulance-ufe:name"}
  newTag: main # {"$imagepolicy": "wac-hospital:boce-wac-project-ambulance-ufe:tag"}

- name: milung/ufe-controller
  newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"}
  newTag: latest # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}